server:
  port: 8081
  error:
    include-message: always
#Configuracion de spring
spring:
  #Configuracion de migracion
  flyway:
    enabled: true
    baselineVersion: 1
    locations:
      classpath: db/migration
    sqlMigrationSuffixes: .sql
    baselineOnMigrate: true
    sqlMigrationPrefix: V
    schemas: public

  datasource:
    url: jdbc:postgresql://babar.db.elephantsql.com:5432/gguxdszc?socketTimeout=3
    username: gguxdszc
    password: aaVqGL8UteMF7pkr-gnU9fvcgPGPVBw3
    driverClassName: org.postgresql.Driver
